#!/usr/bin/python

# work in progress, far from finished
# does some checks on a group of spec files
# -a param to filter on spec files: only check 
#   files which have a certain Authority value
#
# check 1: prdownloadsblabla -> dl.sf.net
# todo:
# check 2: is an Authority specified?
# check 3: is Authority one of atrpms,bob,dag,dries,matthias,newrpms ?
# check 3: check if %{__make} is used instead of make
# todo:
# find more stuff to check :-)



import getopt, os, sys
from pydar import config, log, specfile

config = config()
log = log()
log.loglevel = 2

optlist, args = getopt.getopt(sys.argv[1:], "a:")

if args == []:
	print "check if a specfile is ok"
	print ""
	print "usage: dar-speccheck [ -a authorityname ] specfiles..."
	sys.exit(1)

onlyAuth = ""

if len(optlist) > 0:
	onlyAuth = optlist['a']
	log.debug("only checking files which have " + onlyAuth + " as Authority")
else:
	log.debug("checking all files")


for specfilename in args:
	log.debug("specfilename is " + specfilename)
	myspec = specfile(specfilename, log)
	if myspec.fullcontents.find('prdownloads.sourceforge.net') > -1:
		print specfilename, " uses prdownloads.sourceforge.net, should be dl.sf.net so mach & dar are able to download the file"
