#!/bin/bash

### dar-exec  [ -d <dists> ]  <cmd> ...

source "/usr/lib/dar/dar-functions"

daropts "d:" $@
CMD="$OPTS"

if [ ! -d "$ROOT" ]; then
	echo "ERROR: probably in chroot jail" >&2
	exit 1
fi

set_dists
set_as_root
AS_ROOT=1

for distname in $DISTS; do
	echo "Executing \"$CMD\" for $distname."

	if [ -r "$CONFIGDIR/dists/$dist/config" ]; then
		source "$CONFIGDIR/dists/$dist/config"
	fi

	### Check for building as user
	if [ $AS_ROOT -eq 1 ]; then
		DO_SU="/bin/su - -c"
	else
		DO_SU="/bin/su - -m $BUILD_USER -c"
	fi

	chroot "$CHROOTDIR/$distname" $DO_SU "$CMD"
	RC=$?

	if [ $RC -ne 0 ]; then
		error "Failed executing \"$CMD\" (RC=$RC)"
	fi
	echo
done

exit 0
