#!/bin/bash

source "/usr/lib/dar/dar-functions"

if [ -z "$DEFAULT_DISTS" -o -z "$ROOT" ]; then
	echo "ERROR: There's something wrong with your configuration !" >&2
	exit 1
fi


for distname in $DEFAULT_DISTS; do
	if [ "${DEFAULT_DISTS// */}" != $distname ]; then
		ln -f $CHROOTDIR/${DEFAULT_DISTS// */}/root/.bash_history $CHROOTDIR/$distname/root/.bash_history
	fi
	umount $CHROOTDIR/$distname{/dev/pts,/proc,/tmp,/mnt/dar}/
	mkdir -p $CHROOTDIR/$distname{/dev/pts,/proc,/tmp,/mnt/dar}/
#	rm -rf $CHROOTDIR/$distname{$RPMTMPPATH}/*
	mount -o bind /tmp/ $CHROOTDIR/$distname/tmp/
	mount -o bind $ROOT $CHROOTDIR/$distname/mnt/dar
	mount -t proc proc $CHROOTDIR/$distname/proc/
	mount -t devpts devpts $CHROOTDIR/$distname/dev/pts
done
