#!/bin/bash

### dar-shell  [ -d <dists> ]

source "/usr/share/dar/dar-functions"

daropts "d:" $@
CMD="$OPTS"

if [ ! -d "$ROOT" ]; then
	echo "ERROR: probably in chroot jail" >&2
	exit 1
fi

set_dists
set_as_root
AS_ROOT=1

echo "Entering shells."
for distname in $DISTS; do
	if [ -r "$CONFIGDIR/dists/$distname/config" ]; then
		source "$CONFIGDIR/dists/$distname/config"
		export arch="$DISTARCH" dist="${DISTNAME// *}" nick="$DISTNICK" path="$DISTPATH" repo="$REPO" tag="$TAG"
	fi

	chroot $CHROOTDIR/$distname
done
echo -n "Returning to parent shell. Press ENTER."
read a

exit 0
