#!/bin/bash

### dar-update  [ -a <archs> ]  [ -d <dists> ]  [ -s <sdists> ]  <app> ...

source "/usr/lib/dar/dar-functions"

daropts ":a:d:rs:" $@
PKGS="$OPTS"

#DISTS="$DEFAULT_DISTS"
set_dists

### Update build environment
for distname in $DISTS; do
        if [ -r "$CONFIGDIR/dists/$distname/config" ]; then
                source "$CONFIGDIR/dists/$distname/config"
        else
                warning "Configfile $CONFIGDIR/dists/$distname/config missing. Aborting."
                continue
        fi

	if [ "$CREATE_REPO" == "true" ]; then
		echo "Building $distname repository in $DISTPATH."
		build_repo_apt "$DISTTAG" "$DISTPATH"
#		build_repo_yum "$DISTTAG" "$DISTPATH"
	fi

	echo "Updating $distname."
	if [ "$UPDATECMD" ]; then
		chroot $CHROOTDIR/$distname $UPDATECMD
	fi

	echo "Upgrading $distname."
	if [ "$UPGRADECMD" ]; then
		chroot $CHROOTDIR/$distname $UPGRADECMD
	fi

	if [ "$INSTALLCMD" ]; then
		for pkg in $PKGS; do
			instcmd="$(echo $INSTALLCMD | sed -e "s|%p|$pkg|g")"
	
			echo "Installing $pkg in $distname."
			chroot $CHROOTDIR/$distname $instcmd
		done
	fi
	echo
done
echo "Finished."
