#!/bin/bash

### dar-update  [ -a <archs> ]  [ -d <dists> ]  [ -s <sdists> ]  <app> ...

source "/usr/share/dar/dar-functions"

daropts ":a:d:qrs:" $@
PKGS="$OPTS"

#DISTS="$DEFAULT_DISTS"
set_dists

### Update build environment
for distname in $DISTS; do
    echo "Updating $distname."
    if [ -r "$CONFIGDIR/dists/$distname/config" ]; then
        source "$CONFIGDIR/dists/$distname/config"
    else
        warning "Configfile $CONFIGDIR/dists/$distname/config missing. Aborting."
        continue
    fi

    if [ "$CREATE_REPO" ]; then
        if [ -z "$QUIET" ]; then
            echo "Building $distname repository in $DISTPATH."
        fi
        dar-metadata -q -d $distname
#        build_tree_apt "$DISTNAME $DISTTAG" "$DISTPATH"
#        build_repo_apt "$DISTPATH"
#        build_repo_yum "$DISTTAG" "$DISTPATH"
    fi

    if [ "$UPDATECMD" ]; then
        if [ -z "$FORCE_VERBOSE" ]; then
            echo "$UPDATECMD" | setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/bash --login -s
        else
            echo "$UPDATECMD" | setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/bash --login -x -s
        fi
    fi

    if [ -z "$PKGS" -a "$UPGRADECMD" ]; then
        if [ -z "$FORCE_VERBOSE" ]; then
            echo "$UPGRADECMD" | setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/bash --login -s
        else
            echo "$UPGRADECMD" | setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/bash --login -x -s
        fi
    fi

    if [ "$INSTALLCMD" -a "$PKGS" ]; then
        for pkg in $PKGS; do
            instcmd="$(echo $INSTALLCMD | sed -e "s|%p|$pkg|g")"
            if [ -z "$QUIET" ]; then
                echo "Installing $pkg in $distname."
            fi
            chroot $CHROOTDIR/$distname $instcmd
            if [ -z "$FORCE_VERBOSE" ]; then
                echo "$instcmd" | setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/bash --login -s
            else
                echo "$instcmd" | setarch $DISTARCH /usr/sbin/chroot "$CHROOTDIR/$distname" /bin/bash --login -x -s
            fi
        done
    fi
    echo
done
echo "Finished."
